"""Money layer for BOBCOIN, split by concern:

- ``core``      — Firestore access, atomic transactions, accounts, wallet/house moves
- ``rewards``   — interest, XP, achievements, daily claim, jackpot
- ``loans``     — credit limits, take/repay, interest accrual, AI approval
- ``debt``      — house debt ceiling, auto-borrow, repayment
- ``guardian``  — bank health, luck controls, whale-proof bet cap, force collection

Every public name is re-exported here so existing ``from ..bank import X``
statements keep working unchanged.
"""

from .core import (
    _BANK_FLOOR,
    _Abort,
    _cache,
    _cache_get,
    _cache_set,
    _db,
    _get_db,
    _house_ref,
    _in_txn,
    _parse,
    _positive_amount,
    _ref,
    charge_wallet,
    get_balance,
    get_bank_data,
    get_cooldown,
    get_history,
    get_house_balance,
    get_house_data,
    has_transfer_relation,
    house_payout,
    house_receive,
    is_registered,
    log_history,
    open_account,
    rob_transfer,
    set_cooldown,
    transfer_to_user,
    update_bank,
    user_deposit,
    user_withdraw,
)
from .debt import (
    _debt_ref,
    get_house_debt,
    house_auto_borrow,
    house_repay_debt,
)
from .guardian import (
    get_bank_health,
    get_effective_luck,
    get_lucky_users,
    get_user_luck,
    guardian_force_collect,
    guardian_nerf_user,
    guardian_restore_user,
    house_can_pay_games,
    house_status_band,
    max_bet_allowed,
    set_user_luck,
)
from .loans import (
    accrue_loan_interest,
    ai_loan_limit,
    calc_loan_limit,
    get_loan_info,
    get_total_outstanding_loans,
    repay_loan,
    take_loan,
)
from .rewards import (
    ACHIEVEMENTS,
    add_xp,
    calc_interest,
    contribute_jackpot,
    get_achievements,
    get_jackpot_pool,
    grant_achievement,
    pay_interest_all,
    trigger_jackpot,
    try_daily,
    xp_to_level,
)

__all__ = [
    "ACHIEVEMENTS",
    "_BANK_FLOOR",
    "_Abort",
    "_cache",
    "_cache_get",
    "_cache_set",
    "_db",
    "_debt_ref",
    "_get_db",
    "_house_ref",
    "_in_txn",
    "_parse",
    "_positive_amount",
    "_ref",
    "accrue_loan_interest",
    "add_xp",
    "ai_loan_limit",
    "calc_interest",
    "calc_loan_limit",
    "charge_wallet",
    "contribute_jackpot",
    "get_achievements",
    "get_balance",
    "get_bank_data",
    "get_bank_health",
    "get_cooldown",
    "get_effective_luck",
    "get_history",
    "get_house_balance",
    "get_house_data",
    "get_house_debt",
    "get_jackpot_pool",
    "get_loan_info",
    "get_lucky_users",
    "get_total_outstanding_loans",
    "get_user_luck",
    "grant_achievement",
    "guardian_force_collect",
    "guardian_nerf_user",
    "guardian_restore_user",
    "has_transfer_relation",
    "house_auto_borrow",
    "house_can_pay_games",
    "house_payout",
    "house_receive",
    "house_repay_debt",
    "house_status_band",
    "is_registered",
    "log_history",
    "max_bet_allowed",
    "open_account",
    "pay_interest_all",
    "repay_loan",
    "rob_transfer",
    "set_cooldown",
    "set_user_luck",
    "take_loan",
    "transfer_to_user",
    "trigger_jackpot",
    "try_daily",
    "update_bank",
    "user_deposit",
    "user_withdraw",
    "xp_to_level",
]
